# syntax=docker/dockerfile-upstream:master
FROM --platform=$BUILDPLATFORM python:3.12.9-bullseye AS dependencies-builder
ARG QEMU_PAGESIZE=4096
ENV QEMU_PAGESIZE=$QEMU_PAGESIZE

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TARGET_ARCH=armv7-unknown-linux
ENV TARGET_ARCH_POSTFIX=gnueabihf

RUN getconf PAGE_SIZE && apt update && apt install -y gcc-arm-linux-${TARGET_ARCH_POSTFIX} \
    && pip install -U pip setuptools maturin patchelf ziglang \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ARG CPU_COUNT=4
ENV CPU_COUNT=$CPU_COUNT

WORKDIR /crates-typos
ENV TARGET_TYPOS_TAG=1.29.0
RUN curl -L https://github.com/crate-ci/typos/archive/refs/tags/v${TARGET_TYPOS_TAG}.tar.gz | tar --absolute-names -xzf - && mv typos-${TARGET_TYPOS_TAG} crates-typos
WORKDIR /crates-typos/crates-typos
RUN . $HOME/.cargo/env && rustup target add ${TARGET_ARCH}-${TARGET_ARCH_POSTFIX}
RUN . $HOME/.cargo/env && maturin build -j${CPU_COUNT} --release --manifest-path crates/typos-cli/Cargo.toml --target ${TARGET_ARCH}-${TARGET_ARCH_POSTFIX} --zig

WORKDIR /polars
ARG CARGO_BUILD_JOBS=4
ENV CARGO_BUILD_JOBS=$CARGO_BUILD_JOBS
ENV TARGET_POLARS_TAG=py-1.24.0
RUN curl -L https://github.com/pola-rs/polars/archive/refs/tags/${TARGET_POLARS_TAG}.tar.gz | tar --absolute-names -xzf - && mv polars-${TARGET_POLARS_TAG} polars
WORKDIR /polars/polars
RUN . $HOME/.cargo/env \
    && sed -i "s/--upgrade --compile-bytecode --no-build/--upgrade --compile-bytecode/" /polars/polars/Makefile \
    && sed -i "s/kuzu//" /polars/polars/py-polars/requirements-dev.txt \
    && sed -i "s/deltalake>=0.15.0//" /polars/polars/py-polars/requirements-dev.txt \
    && cd py-polars && make --debug=b -j${CPU_COUNT} requirements \
    && rustup target add ${TARGET_ARCH}-${TARGET_ARCH_POSTFIX}
ARG ALLOCATOR=
ENV ALLOCATOR=$ALLOCATOR
ARG JEMALLOC_SYS_WITH_LG_PAGE=4
ENV JEMALLOC_SYS_WITH_LG_PAGE=$JEMALLOC_SYS_WITH_LG_PAGE
ARG JEMALLOC_SYS_WITH_LG_HUGEPAGE=16
ENV JEMALLOC_SYS_WITH_LG_HUGEPAGE=$JEMALLOC_SYS_WITH_LG_HUGEPAGE
RUN . $HOME/.cargo/env && export RUSTFLAGS=$([ -n "${ALLOCATOR}" ] && echo "--cfg allocator=\"${ALLOCATOR}\"") && maturin build -j${CPU_COUNT} --profile dist-release --manifest-path py-polars/Cargo.toml --target ${TARGET_ARCH}-${TARGET_ARCH_POSTFIX} --zig




FROM python:3.12.9-bullseye AS tg-zmt-bot_dependencies_armv7
COPY --from=dependencies-builder /polars/polars/target/wheels /wheels
COPY --from=dependencies-builder /crates-typos/crates-typos/target/wheels /wheels
RUN ls /wheels

